routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

//******************************* DASHBOARD ROUTES  ***********************************

//DASHBOARD LOGIN

Route::group(['prefix' => 'dashboard-login', 'as' => 'login.', 'namespace' => 'Admin'], function () {
    Route::get('/', 'LoginController@showLogin')->name('login');
    Route::post('/', 'LoginController@Login');
});


Route::group(['prefix' => 'dashboard', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {


    //Home 
    Route::get('/', 'IndexController@index')->name('home')->middleware('role:home');

    //USERS and Users Operations
    Route::resource('admins', 'AdminController')->middleware('role:admins');
    Route::get('admins/delete/{id}', 'UsersController@AdminDelete')->middleware('role:admins');


    Route::resource('clients', 'UsersController')->middleware('role:clients');
    Route::get('clients/delete/{id}', 'UsersController@UserDelete')->middleware('role:clients');

    //Albums
    Route::resource('albums', 'UserAlbumsController')->middleware('role:albums');


    //GROUPS AND PERMISSIONS
    Route::resource('groups', 'GroupsController')->middleware('role:groups');

});


//******************************* WEBSITE ROUTES  ***********************************

Route::group(['prefix' => '/', 'as' => 'website.', 'namespace' => 'Website'], function () {

    Route::get('/', 'IndexController@Albums')->name('Album');

    //PROFILE
    Route::get('profile', 'IndexController@Profile')->name('profile');
    Route::get('profile-edit', 'IndexController@EditProfile')->name('EditProfile');
    Route::post('update', 'IndexController@UpdateProfile')->name('UpdateProfile');

    //AJaxRoutes
    Route::get('album/delete/{id}', 'AjaxOperationsController@UserAlbumDelete');


});

app/Http/Controllers/Admin/AlbumsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\UserAlbum;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AlbumsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $albums=UserAlbum::all();
        return view('admin.albums.index',['items'=>$albums]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/albums/index.blade.php
@extends('admin.layout.app')

@section('title')
    صور الألبومات
@endsection
@section('header')
    @include('admin.datatable.headers')
@endsection
@section('content')
    @include('admin.common.alert')
    <!-- Exportable Table -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        أعضاء إدارة النظام
                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <a href="{{route('admin.admins.create')}}">
                            <button class="btn btn-success">إضافة عضو جديد</button>
                        </a>
                    </ul>
                </div>
                <div class="body">
                    <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>الإسم</th>
                            <th>الايميل</th>

                            <th>العمليات</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($items as $key=>$item)
                            <tr>
                                <td>{{++$key}}</td>
                                <td>{{$item->name}}</td>
                                <td>{{$item->email}}</td>
                                <td>
                                    <a href="{{route('admin.admins.edit',['id'=>$item->id])}}"
                                       class="btn btn-info btn-circle"><i style="padding-top:5px;padding-left: 6px;"
                                                                          class="fa fa-pencil"></i></a>
                                    @if($item->email== "admin@admin.com")
                                    @else
                                        <a href="#" onclick="Delete({{$item->id}})" data-toggle="tooltip"
                                           data-original-title="حذف" class="btn btn-danger btn-circle"><i
                                                    style="padding-top: 5px;padding-left: 4px;"
                                                    class="fa fa-trash-o"></i></a>
                                    @endif
                                    {!!Form::open( ['route' => ['admin.admins.destroy',$item->id] ,'id'=>'delete-form'.$item->id, 'method' => 'Delete']) !!}
                                    {!!Form::close() !!}


                                </td>

                            </tr>
                        @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Exportable Table -->

@endsection

@section('footer')
    @include('admin.datatable.scripts')
    <script>
        function Delete(id) {
            var item_id = id;
            console.log(item_id);
            swal({
                title: "هل أنت متأكد ",
                text: "هل تريد حذف هذا الأدمن ؟",
                icon: "warning",
                buttons: ["الغاء", "موافق"],
                dangerMode: true,

            }).then(function (isConfirm) {
                if (isConfirm) {
                    document.getElementById('delete-form' + item_id).submit();
                } else {
                    swal("تم االإلفاء", "حذف  الأدمن تم الغاؤه", 'info', {buttons: 'موافق'});
                }
            });
        }
    </script>
@endsection