routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

//******************************* DASHBOARD ROUTES  ***********************************

//DASHBOARD LOGIN

Route::group(['prefix' => 'dashboard-login', 'as' => 'login.', 'namespace' => 'Admin'], function () {
    Route::get('/', 'LoginController@showLogin')->name('login');
    Route::post('/', 'LoginController@Login');
});


Route::group(['prefix' => 'dashboard', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {


    //Home 
    Route::get('/', 'IndexController@index')->name('home')->middleware('role:home');

    //USERS and Users Operations
    Route::resource('admins', 'AdminController')->middleware('role:admins');
    Route::get('admins/delete/{id}', 'UsersController@AdminDelete')->middleware('role:admins');


    Route::resource('clients', 'UsersController')->middleware('role:clients');
    Route::get('clients/delete/{id}', 'UsersController@UserDelete')->middleware('role:clients');

    //Albums
    Route::resource('albums', 'UserAlbumsController')->middleware('role:albums');


    //GROUPS AND PERMISSIONS
    Route::resource('groups', 'GroupsController')->middleware('role:groups');

});


//******************************* WEBSITE ROUTES  ***********************************

Route::group(['prefix' => '/', 'as' => 'website.', 'namespace' => 'Website'], function () {

    Route::get('/', 'IndexController@Albums')->name('Album');

    //PROFILE
    Route::get('profile', 'IndexController@Profile')->name('profile');
    Route::get('profile-edit', 'IndexController@EditProfile')->name('EditProfile');
    Route::post('update', 'IndexController@UpdateProfile')->name('UpdateProfile');

    //AJaxRoutes
    Route::get('album/delete/{id}', 'AjaxOperationsController@UserAlbumDelete');


});

resources/views/admin/clients/add.blade.php
@extends('admin.layout.app')

@section('title')
إضافة  عميل جديد
@endsection
@section('content')

<!-- Basic Validation -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>إضافة عميل جديد</h2>
        <ul class="header-dropdown m-r--5">
            <a href="{{route('admin.clients.index')}}">   <button class="btn btn-danger">كل العملاء </button></a>
</ul>
      </div>
      <div class="body">
          {!!Form::open( ['route' => 'admin.clients.store' ,'class'=>'form phone_validate', 'method' => 'Post','files' => true]) !!}
            @include('admin.clients.form')
          {!!Form::close() !!}
      </div>
    </div>
  </div>
</div>
<!-- #END# Basic Validation -->
@endsection

resources/views/admin/clients/edit.blade.php
@extends('admin.layout.app')

@section('title')
    تعديل العميل
    {{ $item->name }}
@endsection
@section('content')

    <!-- Basic Validation -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>تعديل العميل {{ $item->name }}</h2>
                    <ul class="header-dropdown m-r--5">
                        <a href="{{route('admin.clients.index')}}">
                            <button class="btn btn-danger">كل العملاء</button>
                        </a>
                    </ul>
                </div>
                <div class="body">
                    {!!Form::model($item , ['route' => ['admin.clients.update' , $item->id] , 'method' => 'PATCH','enctype'=>"multipart/form-data",'files' => true]) !!}
                    @include('admin.clients.form')
                    {!!Form::close() !!}
                </div>
            </div>
        </div>
    </div>


    <!-- #END# Basic Validation -->
@endsection

resources/views/admin/clients/form.blade.php
@include('admin.common.alert')
@include('admin.common.errors')


<div class="form-group form-float">
  <label class="form-label">الإسم</label>
  <div class="form-line">
    {!! Form::text("name",null,['class'=>'form-control','placeholder'=>'  الاسم  '])!!}
  </div>
</div>

<div class="form-group form-float">
  <label class="form-label">الإيميل</label>
  {!! Form::email("email",null,['class'=>'form-control','placeholder'=>'  الايميل '])!!}
  <div class="form-line">
  </div>
</div>


<div class="form-group form-float">
    <label >الجوال </label>
    {!! Form::text("phone",null,['class'=>'form-control','placeholder'=>'  الجوال  '])!!}
    <div class="form-line">
    </div>
</div>

<div class="form-group form-float">
  <label class="form-label">كلمة المرور</label>
    {!! Form::input('password','password',null,['class'=>'form-control','placeholder'=>'كلمة المرور']) !!}
    <div class="form-line">
  </div>
</div>

<div class="form-group form-float">
  <label class="form-label">تكرار كلمة المرور</label>
    {!! Form::input('password','password_confirmation',null,['class'=>'form-control','placeholder'=>'تكرار كلمة المرور']) !!}

    <div class="form-line">
  </div>
</div>


    <div class="form-group">
        {!! Form::radio("is_active",1,null,['class'=>'with-gap','id'=>'radio_3']) !!}
        <label for="radio_3"> تفعيل </label>

        {!! Form::radio("is_active",0,null,['class'=>'with-gap','id'=>'radio_4']) !!}
        <label for="radio_4" >عدم تفعيل</label>
    </div>

{!! Form::input('hidden','role','client',['class'=>'form-control']) !!}

@if(isset($item->id))
{!! Form::input('hidden','id',$item->id,['class'=>'form-control']) !!}
@endif
<button class="btn btn-primary waves-effect" type="submit">حفظ</button>

resources/views/admin/clients/index.blade.php
@extends('admin.layout.app')

@section('title')
    جميع المستخدمين
@endsection
@section('header')
    @include('admin.datatable.headers')
@endsection
@section('content')
    @include('admin.common.alert')
    <!-- Exportable Table -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        جميع المستخدمين
                    </h2>
                </div>
                <div class="body">
                    <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>الاسم</th>
                            <th>الايميل</th>
                            <th>حذف المستخدم</th>
                            <th>مشاهدة الألبوم</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($items as $key=>$item)
                            <tr>
                                <td>{{++$key}}</td>
                                <td>{{$item->name}}</td>
                                <td>{{$item->email}}</td>
                                <td>

                                    <a onclick="goDoSomething(this)" data-id="{{$item->id}}"
                                       class=" delete btn btn-danger"><i
                                                class="fa fa-trash-o"></i></a>


                                </td>
                                <td>

                                    <a href="{{route('admin.clients.show',['id'=>$item->id])}}"
                                       class="btn btn-info btn-circle">
                                        <i style="padding-top:5px;padding-left: 6px;"
                                           class="fa fa-eye"></i>
                                    </a>
                                </td>


                            </tr>
                        @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Exportable Table -->

@endsection

@section('footer')
    @include('admin.datatable.scripts')
    <script>


        function goDoSomething(identifier) {

            alert('hi');
            $.ajax({
                url: "{{asset('/dashboard/clients/delete')}}" + "/" + $(identifier).data('id'),
                success: function (result) {
                    window.location.reload();
                }
            });

        }
    </script>
@endsection

resources/views/admin/clients/show.blade.php
@extends('admin.layout.app')

@section('title')
    جميع المستخدمين
@endsection
@section('header')
    @include('admin.datatable.headers')
@endsection
@section('content')
    @include('admin.common.alert')
    <!-- Exportable Table -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        جميع الصور الخاصة ب {{$item->name}}
                    </h2>
                </div>
                <div class="body">
                    <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>الصورة</th>
                            <th>الحالة</th>
                            <th>حذف الصورة</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($item->Album as $key=>$album)
                            <tr>
                                <td>{{++$key}}</td>
                                <td>
                                    <img src="{{$album->file}}" style="height: 50px; width: 50px">
                                </td>
                                <td>{{$album->status}}</td>
                                <td>

                                    <a onclick="goDoSomething(this)" data-id="{{$album->id}}"
                                       class=" delete btn btn-danger"><i
                                                class="fa fa-trash-o"></i></a>


                                </td>


                            </tr>
                        @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Exportable Table -->

@endsection

@section('footer')
    @include('admin.datatable.scripts')
    <script>


        function goDoSomething(identifier) {

            // alert('hi');
            $.ajax({
                url: "{{asset('/album/delete')}}" + "/" + $(identifier).data('id'),
                success: function (result) {
                    window.location.reload();
                }
            });

        }
    </script>
@endsection