routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

//******************************* DASHBOARD ROUTES  ***********************************

//DASHBOARD LOGIN

Route::group(['prefix' => 'dashboard-login', 'as' => 'login.', 'namespace' => 'Admin'], function () {
    Route::get('/', 'LoginController@showLogin')->name('login');
    Route::post('/', 'LoginController@Login');
});


Route::group(['prefix' => 'dashboard', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {


    //Home 
    Route::get('/', 'IndexController@index')->name('home')->middleware('role:home');

    //USERS and Users Operations
    Route::resource('admins', 'AdminController')->middleware('role:admins');
    Route::get('admins/delete/{id}', 'UsersController@AdminDelete')->middleware('role:admins');


    Route::resource('clients', 'UsersController')->middleware('role:clients');
    Route::get('clients/delete/{id}', 'UsersController@UserDelete')->middleware('role:clients');

    //Albums
    Route::resource('albums', 'UserAlbumsController')->middleware('role:albums');


    //GROUPS AND PERMISSIONS
    Route::resource('groups', 'GroupsController')->middleware('role:groups');

});


//******************************* WEBSITE ROUTES  ***********************************

Route::group(['prefix' => '/', 'as' => 'website.', 'namespace' => 'Website'], function () {

    Route::get('/', 'IndexController@Albums')->name('Album');

    //PROFILE
    Route::get('profile', 'IndexController@Profile')->name('profile');
    Route::get('profile-edit', 'IndexController@EditProfile')->name('EditProfile');
    Route::post('update', 'IndexController@UpdateProfile')->name('UpdateProfile');

    //AJaxRoutes
    Route::get('album/delete/{id}', 'AjaxOperationsController@UserAlbumDelete');


});

app/Http/Controllers/Website/AjaxOperationsController.php
<?php

namespace App\Http\Controllers\Website;

use App\UserAlbum;
use App\Http\Controllers\Controller;

class AjaxOperationsController extends Controller
{



    public function UserAlbumDelete($id)
    {
        $image = UserAlbum::find($id);
        if ($image) {
            $image->delete();
            return "image deleted";
        } else {
            return "not found";
        }


    }

}

app/Http/Controllers/Website/IndexController.php
<?php

namespace App\Http\Controllers\Website;

use App\Http\Controllers\Controller;
use App\Http\Requests\ClientsRequest;
use App\Http\Traits\UsersOperations;
use App\UserAlbum;
use Hash;

class IndexController extends Controller
{
    use UsersOperations;

    public function Albums()
    {
        if (auth()->check()) {
            $albums = UserAlbum::where('user_id', auth()->user()->id)->get();
        } else {
            $albums = UserAlbum::whereStatus('public')->get();
        }
        return view('website.albums', ['items' => $albums]);
    }


    public function Profile()
    {
        return view('website.profile');
    }


    public function EditProfile()
    {
        $images = UserAlbum::where('user_id', auth()->user()->id)->get();
        return view('website.edit_profile', ['images' => $images]);
    }

    public function UpdateProfile(ClientsRequest $request)
    {
        $user = auth()->user();

        if (Hash::check($request->old_password, auth()->user()->password)) {
//            dd('hi');
            $this->UpdateUser($user, $request);
        } else {
            alert()->error('كلمة المرور القديمة غير صحيحة !')->autoclose(5000);
            return back();
        }
        popup('update');
        return back();
    }
}

resources/views/website/albums.blade.php
@extends('website.layout.master')

@section('title')
    Albums
@stop


@section('content')

    <section class="check_demo_movie">
        <div class="container">
            <h2 class=" wow fadeInDown">Album <span class="main-color"> Sharing</span></h2>
            <div class="row">
                @forelse($items as $item)

                    <div class="col-md-4">
                        <div class="card wow fadeInUp" data-wow-duration="0.5s" data-wow-delay="0.5s">
                            <div class="card-header">
                                <img src="{{$item->file}}" class="lazyload">
                            </div>
                        </div>
                    </div>
                @empty
                    Sorry, There are No Albums Now..
                @endforelse

            </div>
        </div>
    </section>

@stop

resources/views/website/edit_profile.blade.php
@extends('website.layout.master')

@section('title')
    EditProfile
@stop

@section('headers')
    <style>
        #clickableAwesomeFont {
            cursor: pointer
        }
    </style>
    @endsection

@section('content')


    <section class="profile bkg">
        <div class="container">

            @include('admin.common.alert')
            @include('admin.common.errors')
            <form class="form2 width-80 form-no-hover" action="{{route('website.UpdateProfile')}}" method = "POST"  enctype="multipart/form-data">

                @csrf

                <div class="row">


                    <div class="col-12">
                        <div class="form-group">
                            <label> اسم المستخدم </label>
                            <input name="name" type="text"  id="name" class="form-control" value="{{auth()->user()->name}}">
                            <span class="focus-border"></span>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <label> البريد الإلكترونى </label>
                            <input type="email" name="email"  id="email" class="form-control" value="{{auth()->user()->email}}">
                            <span class="focus-border"></span>
                        </div>
                    </div>

                    <div class="col-12">
                        <div class="form-group">
                            <label> Old Password </label>
                            <input type="password" class="form-control" id="password" name="old_password">
                            <span class="focus-border"></span>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <label>New Password </label>
                            <input type="password" class="form-control" id="pwd" name="password">
                            <span class="focus-border"></span>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <label> password Confirmation </label>
                            <input type="password" class="form-control" id="pwd" name="password_confirmation">
                            <span class="focus-border"></span>
                        </div>
                    </div>


                    @if (isset($images))
                        <div class="col-12">
                            <div class="form-group form-float">
                                <label class="form-label">الصور الحالية :</label>
                                <div class="form-line row">
                                    @foreach($images as $image)
                                        <div class="col-sm-3">
                                            <div class="flex-img">
                                                <img class="img-preview" src="{{$image->file}}"
                                                     style="height: 50px; width: 50px">
                                                <div class="row ">
                                                    {{--                            @dd($image->id)--}}
                                                    <span onclick="goDoSomething(this)" data-id="{{$image->id}}" id='clickableAwesomeFont'
                                                          class=" delete btn btn-danger"><i class="fas fa-trash"></i></span>
                                                </div>
                                            </div>
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                        </div>
                    @endif


                    <div class="col-12">
                        <label class="form-label">اضافة صور للألبوم</label>
                        <div class="form-line">
                            {!!Form::file('files[]', ['class'=>'form-control','multiple'=>'yes','id'=>'file'])!!}
                        </div>
                    </div>

                    <br><hr><hr>
                    <div class="col-12">
                        <div class="col-12">
                            <label class="form-label">نوع الألبوم </label>
                            {!! Form::radio("status",'private',null,['class'=>'with-gap','id'=>'radio_3']) !!}
                            <label for="radio_3"> خاصة </label>

                            {!! Form::radio("status",'public',null,['class'=>'with-gap','id'=>'radio_4']) !!}
                            <label for="radio_4">عامة</label>
                        </div>
                    </div>
                    {!! Form::input('hidden','id',auth()->user()->id,['class'=>'form-control']) !!}
                    <div class="text-center p-2">
                        <button type="submit" class="btn btn-gradiant">
                            Save
                        </button>
                    </div>

                </div>

            </form>

        </div>
    </section>

@stop

@push('scripts')
    <script>

        {{--$("#update").on("click", function (e) {--}}

            {{--// alert('hi');--}}
            {{--e.preventDefault();--}}
            {{--$.post('/update', {--}}
                {{--_token:"{{csrf_token()}}",--}}
                {{--name: $("#name").val(),--}}
                {{--email: $("#email").val(),--}}
                {{--password: $("#password").val(),--}}
                {{--password_confirmation: $("#password_confirmation").val(),--}}
                {{--file: $("#file").val()--}}
            {{--}, function(data) {--}}
                {{--if (data.response == '/'){--}}
                    {{--window.location.href = '/profile-edit';--}}
                {{--} else{--}}
                    {{--alert(data.response);--}}
                {{--}--}}
            {{--});--}}
        {{--});--}}

        function goDoSomething(identifier) {
            $.ajax({
                url: "{{asset('/album/delete')}}" + "/" + $(identifier).data('id'),
                success: function (result) {
                    window.location.reload();
                }
            });

        }
    </script>
@endpush

resources/views/website/profile.blade.php
@extends('website.layout.master')

@section('title')
    Profile
@stop


@section('content')

    <section class="profile bkg">
        <div class="container">

            <form class="form2 width-80 form-no-hover">

                <div class="input-group-text">

                </div>
                <div class="col-12">
                    <div class="form-group">
                        <label> اسم المستخدم </label>
                        <input type="text" class="form-control" readonly value="{{auth()->user()->name}}">
                        <span class="focus-border"></span>
                    </div>
                </div>

                <div class="col-12">
                    <div class="form-group">
                        <label> البريد الإلكترونى </label>
                        <input type="email" class="form-control" readonly value="{{auth()->user()->email}}">
                        <span class="focus-border"></span>
                    </div>
                </div>

                <section class="check_demo_movie">
                    <div class="container">
                        <h2 class=" wow fadeInDown">Albums <span class="main-color"> Sharing</span></h2>
                        <p>User Albums</p>
                        <div class="row">

                            @forelse(auth()->user()->Album as $item)
                                <div class="col-md-4">
                                    <div class="card wow fadeInUp" data-wow-duration="0.5s" data-wow-delay="0.5s">
                                        <div class="card-header">
                                            <img src="{{$item->file}}" class="lazyload">
                                        </div>
                                        <div class="card-body">
                                            <p class="package-price">
                                                type : {{$item->status}}
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            @empty
                             Their are No Albums Tell Now
                            @endforelse


                        </div>
                    </div>
                    <a href="{{route('website.EditProfile')}}">
                    <button class="btn btn-gradiant m-0">
                        Edit Profile
                    </button>
                    </a>
                </section>

            </form>
        </div>


    </section>

@stop