routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

//******************************* DASHBOARD ROUTES  ***********************************

//DASHBOARD LOGIN

Route::group(['prefix' => 'dashboard-login', 'as' => 'login.', 'namespace' => 'Admin'], function () {
    Route::get('/', 'LoginController@showLogin')->name('login');
    Route::post('/', 'LoginController@Login');
});


Route::group(['prefix' => 'dashboard', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {


    //Home 
    Route::get('/', 'IndexController@index')->name('home')->middleware('role:home');

    //USERS and Users Operations
    Route::resource('admins', 'AdminController')->middleware('role:admins');
    Route::get('admins/delete/{id}', 'UsersController@AdminDelete')->middleware('role:admins');


    Route::resource('clients', 'UsersController')->middleware('role:clients');
    Route::get('clients/delete/{id}', 'UsersController@UserDelete')->middleware('role:clients');

    //Albums
    Route::resource('albums', 'UserAlbumsController')->middleware('role:albums');


    //GROUPS AND PERMISSIONS
    Route::resource('groups', 'GroupsController')->middleware('role:groups');

});


//******************************* WEBSITE ROUTES  ***********************************

Route::group(['prefix' => '/', 'as' => 'website.', 'namespace' => 'Website'], function () {

    Route::get('/', 'IndexController@Albums')->name('Album');

    //PROFILE
    Route::get('profile', 'IndexController@Profile')->name('profile');
    Route::get('profile-edit', 'IndexController@EditProfile')->name('EditProfile');
    Route::post('update', 'IndexController@UpdateProfile')->name('UpdateProfile');

    //AJaxRoutes
    Route::get('album/delete/{id}', 'AjaxOperationsController@UserAlbumDelete');


});

resources/views/admin/layout/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>لوحة التحكم - @yield('title')</title>
    @yield('header')
    @include('admin.layout.styles')

</head>

<body class="theme-red">
<!-- Page Loader -->
<div class="page-loader-wrapper">
    <div class="loader">
        <div class="preloader">
            <div class="spinner-layer pl-red">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
               
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
             <i class="fas fa-futbol"></i>
        </div>
        <p>رجاءً انتظر...</p>
    </div>
</div>
<!-- #END# Page Loader -->

<!-- Overlay For Sidebars -->
<div class="overlay"></div>
<!-- #END# Overlay For Sidebars -->

<!-- Top Bar -->
<nav class="navbar">
     <div class="logo-dashboard text-center">
            
        </div>
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="javascript:void(0);" class="bars"></a>
            <a class="navbar-brand" href="/"></a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
            </ul>
        </div>
       
        
    </div>
</nav>
<!-- #Top Bar -->

<section>
    <!-- Left Sidebar -->
    <aside id="leftsidebar" class="sidebar">
        <!-- User Info -->
        <div class="user-info">
             <div class="image">
            <img src="{{url('admin/images/user.png')}}" width="48" height="48" alt="User" />
        </div>
            <div class="info-container">
                <div class="name ar" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></div>
                <div class="email ar"></div>
                <div class="btn-group user-helper-dropdown">
                    <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                    <ul class="dropdown-menu pull-left">
                        <form id="logout-form" action="{{route('logout')}}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                        <li><a class="ar" onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();" href="{{url('/logout')}}"><i
                                        class="material-icons">input</i>تسجيل الخروج</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- #User Info -->
        <!-- Menu -->
        <div class="menu">
            <ul class="list">
                <li class="header">القائمة الرئيسية</li>
                @include('admin.layout.nav')
            </ul>
        </div>
        <!-- #Menu -->
    </aside>
    <!-- #END# Left Sidebar -->
</section>

<section class="content">
    <div class="container-fluid">
        @yield('content')
        @include('sweet::alert')
    </div>
</section>


@include('admin.layout.scripts')

@yield('footer')
@stack('scripts')

</body>
</html>

resources/views/admin/layout/home.blade.php
@extends('admin.layout.app')

@section('title')
    الصفحه الرئيسه
@endsection

@section('content')
    <!-- Widgets -->
    <div class="row clearfix">

        <a href="{{route('admin.admins.index')}}" style="color:#eee">
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="info-box bg-lime hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">assignment_ind</i>
                </div>

                <div class="content">
                    <div class="text">
                      عدد أعضاء إدارة النظام
                    </div>
                    <div class="number count">{{\App\User::where('role','admin')->count()}}</div>
                </div>

            </div>
        </div>
        </a>





        <a href="{{route('admin.clients.index')}}" style="color:#eee">
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="info-box bg-lime hover-expand-effect">
                    <div class="icon">
                        <i class="material-icons">assignment_ind</i>
                    </div>

                    <div class="content">
                        <div class="text">
                            عدد المستخدمين
                        </div>
                        <div class="number count">{{\App\User::where('role','user')->count()}}</div>
                    </div>

                </div>
            </div>
        </a>

        <a href="{{route('admin.groups.index')}}" style="color:#eee">
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="info-box bg-lime hover-expand-effect">
                    <div class="icon">
                        <i class="material-icons">assignment_ind</i>
                    </div>

                    <div class="content">
                        <div class="text">
                             عدد المجموعات
                        </div>
                        <div class="number count">{{\App\Group::count()}}</div>
                    </div>

                </div>
            </div>
        </a>


        <a href="{{route('admin.groups.index')}}" style="color:#eee">
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="info-box bg-lime hover-expand-effect">
                    <div class="icon">
                        <i class="material-icons">assignment_ind</i>
                    </div>

                    <div class="content">
                        <div class="text">
                            عدد الألبومات
                        </div>
                        <div class="number count">{{\App\UserAlbum::count()}}</div>
                    </div>

                </div>
            </div>
        </a>



    </div>


@endsection

@push('scripts')

    @endpush

resources/views/admin/layout/nav.blade.php
<?php
$home = $clients = $admins= $groups=$albums = FALSE;
if(isset(auth()->user()->Group->Permissions)){
foreach (auth()->user()->Group->Permissions as $pre) {
    if ($pre['name'] == "groups") {
        $groups = TRUE;
    }
    elseif ($pre['name'] == "home") {
        $home = TRUE;
    } elseif ($pre['name'] == "admins") {
        $admins = TRUE;
    }  elseif ($pre['name'] == "clients") {
        $clients = TRUE;
    }elseif ($pre['name'] == "albums") {
        $albums = TRUE;
    }
}
}
?>

<li>
    <a class="check_active" href="{{route('website.Album')}}">
        <i class="material-icons">home</i>
        <span>الموقع</span>
    </a>

</li>
@if($home)
    <li>
        <a class="check_active" href="{{route('admin.home')}}">
            <i class="material-icons">home</i>
            <span>الصفحه الرئيسه والاحصائيات</span>
        </a>

    </li>
@endif

@if($admins ||$clients)
<li class="header"> ادارة المستخدمين</li>
@endif
    @if($admins)
        <li>
            <a href="javascript:void(0);" class="menu-toggle">
                <i class="material-icons">assignment_ind</i>
                <span>أعضاء الإدارة</span>
            </a>
            <ul class="ml-menu">
                <li>
                    <a class="check_active" href="{{route('admin.admins.index')}}">

                        <span>  أعضاء الإدارة</span>
                    </a>
                </li>
            </ul>
        </li>
    @endif


    @if($clients)
        <li>
            <a href="javascript:void(0);" class="menu-toggle">
                <i class="material-icons">assignment_ind</i>
                <span>العملاء</span>
            </a>
            <ul class="ml-menu">
                <li>
                    <a class="check_active" href="{{route('admin.clients.index')}}">

                        <span>  جميع المستخدمين</span>
                    </a>
                </li>
            </ul>
        </li>

    @endif




@if($groups)
<li class="header"> إعدادات النظام والصلاحيات</li>
@endif
@if($groups)
    <li>
        <a href="javascript:void(0);" class="menu-toggle">
            <i class="material-icons">view_list</i>
            <span> المجموعات</span>
        </a>
        <ul class="ml-menu">
            <li>
                <a class="check_active" href="{{route('admin.groups.index')}}">
                    <span> عرض جميع المجموعات</span>
                </a>
            </li>
            <li>
                <a class="check_active" href="{{route('admin.groups.create')}}">
                    <span> اضافه مجموعة</span>
                </a>
            </li>
        </ul>
    </li>
@endif

resources/views/admin/layout/scripts.blade.php
<!-- Multi Select Plugin Js -->


<!-- Jquery Core Js -->
{{--{!!Html::script('admin/plugins/animate-css/animate.min.css')!!}--}}
{!!Html::script('admin/plugins/jquery/jquery.min.js')!!}
<!-- Bootstrap Core Js -->
{!!Html::script('admin/plugins/bootstrap/js/bootstrap.min.js')!!}
<!-- Select Plugin Js -->
{!!Html::script('admin/plugins/bootstrap-select/js/bootstrap-select.min.js')!!}
<!-- Slimscroll Plugin Js -->
{!!Html::script('admin/plugins/jquery-slimscroll/jquery.slimscroll.min.js')!!}
<!-- Waves Effect Plugin Js -->
{!!Html::script('admin/plugins/node-waves/waves.min.js')!!}
<!-- Custom Js -->
{!!Html::script('admin/js/admin.js')!!}
{!!Html::script('admin/cus/sweetalert.min.js')!!}
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script type="text/javascript">
    var lis = $('.check_active');

    lis.each(function(index){
        if($(this).attr('href') === "{!!url('/')!!}" + window.location.pathname){
            $(this).parent().addClass('active');
            $(this).parent().parent().parent().addClass('active');

        }
        // console.log($(this).attr('href'));
    });
</script>
<script type="text/javascript">
    $(window).load(function() {
        if($( window ).width() < 481){
            $('.dt-buttons').hide();
        }
    });
</script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/noty/3.1.4/noty.js"></script>

@if(Session::has('success'))
    <script>
        new Noty({
            type: 'info',
            layout: 'topRight',
            text: '{!! Session::get('success') !!}'
        }).show();
    </script>
@elseif(Session::has('error'))
    <script>
        new Noty({
            type: 'error',
            layout: 'topRight',
            text: '{!! Session::get('error') !!}'
        }).show();
    </script>
@endif

resources/views/admin/layout/styles.blade.php
<!-- Favicon-->
<!-- <link rel="icon" href="favicon.ico" type="image/x-icon"> -->

<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Changa" rel="stylesheet">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />


<!-- Multi Select Css -->
{!!Html::style('admin/plugins/multi-select/css/multi-select.css')!!}
<!-- Bootstrap Core Css -->
{!!Html::style('admin/plugins/bootstrap/css/bootstrap.min.css')!!}
<!-- Waves Effect Css -->
{!!Html::style('admin/plugins/node-waves/waves.min.css')!!}
<!-- Animation Css -->
{{--{!!Html::style('admin/plugins/animate-css/animate.min.css')!!}--}}
<!-- Custom Css -->
{!!Html::style('admin/css/style.min.css')!!}
<!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
{!!Html::style('admin/css/themes/theme-red.min.css')!!}
{!!Html::style('admin/css/rtl.css')!!}
{!!Html::style('admin/cus/sweetalert.css')!!}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/noty/3.1.4/noty.min.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>


<style>
    /* .navbar {
         background-color: #f7921f !important;
     }*/
    .sidebar .user-info {
        height: 82px;
    }
</style>